# Generated by Django 5.1.7 on 2025-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
    ]
