# Generated by Django 5.1.7 on 2025-03-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_datesvalues'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datesvalues',
            unique_together={('date', 'stock')},
        ),
    ]
