# Generated by Django 5.1.7 on 2025-03-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_datesvalues_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
