# Generated by Django 5.1.7 on 2025-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesvalues',
            name='adj_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
