# Generated by Django 5.1.7 on 2025-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_datesvalues_adj_close'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesvalues',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datesvalues',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datesvalues',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datesvalues',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datesvalues',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
