# Generated by Django 5.1.7 on 2025-03-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_datesvalues_close_alter_datesvalues_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
