# Generated by Django 5.1.7 on 2025-03-22 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_stock_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesvalues',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_values', to='stocks.stock'),
        ),
    ]
